apiVersion: apps/v1
kind: Deployment
metadata:
  name: reserveOK
  labels:
    app: reserveOK
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reserveOK
  template:
    metadata:
      labels:
        app: reserveOK
    spec:
      containers:
        - name: reserveOK
          image: username/reserveOK:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5